package org.example.storage;

import org.example.quik.dto.QuikMessage;
import org.example.quik.json.QuikJson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;

/**
 * Локальный файл H2 в каталоге пользователя {@code ~/.quikclient/quik.*} — ответы RPC и колбеки для последующей обработки.
 */
public final class H2QuikRepository implements AutoCloseable {

    static {
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            throw new ExceptionInInitializerError(new IllegalStateException(
                    "В classpath нет драйвера H2. Соберите fat-jar: mvn package, затем java -jar target/QuikClient-*-all.jar", e));
        }
    }

    private final String jdbcUrl;
    private Connection connection;

    public H2QuikRepository() throws SQLException, IOException {
        Path dir = Path.of(System.getProperty("user.home"), ".quikclient");
        Files.createDirectories(dir);
        Path base = dir.resolve("quik");
        String path = base.toAbsolutePath().toString().replace('\\', '/');
        this.jdbcUrl = "jdbc:h2:file:" + path + ";DB_CLOSE_DELAY=-1;AUTO_SERVER=FALSE";
        this.connection = DriverManager.getConnection(jdbcUrl);
        initSchema(connection);
    }

    private static void initSchema(Connection c) throws SQLException {
        try (Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS quik_rpc_result (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      operation VARCHAR(256) NOT NULL,
                      request_payload CLOB,
                      response_json CLOB NOT NULL,
                      lua_error VARCHAR(2048),
                      created_at TIMESTAMP NOT NULL
                    )""");
            st.execute("""
                    CREATE TABLE IF NOT EXISTS quik_callback (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      cmd VARCHAR(256) NOT NULL,
                      payload_json CLOB NOT NULL,
                      created_at TIMESTAMP NOT NULL
                    )""");
            st.execute("CREATE INDEX IF NOT EXISTS idx_quik_rpc_created ON quik_rpc_result(created_at)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_quik_cb_created ON quik_callback(created_at)");
        }
    }

    public synchronized void saveRpc(String operation, String requestPayload, QuikMessage response) throws IOException, SQLException {
        String json = QuikJson.mapper().writeValueAsString(response);
        String luaErr = response.getLuaError();
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO quik_rpc_result(operation, request_payload, response_json, lua_error, created_at) VALUES (?,?,?,?,?)")) {
            ps.setString(1, operation);
            ps.setString(2, requestPayload);
            ps.setString(3, json);
            ps.setString(4, luaErr);
            ps.setTimestamp(5, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        }
    }

    public synchronized void saveCallback(QuikMessage msg) throws IOException, SQLException {
        String json = QuikJson.mapper().writeValueAsString(msg);
        String cmd = msg.getCmd() != null ? msg.getCmd() : "";
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO quik_callback(cmd, payload_json, created_at) VALUES (?,?,?)")) {
            ps.setString(1, cmd);
            ps.setString(2, json);
            ps.setTimestamp(3, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        }
    }

    public String jdbcUrl() {
        return jdbcUrl;
    }

    @Override
    public synchronized void close() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
            connection = null;
        }
    }
}
