package org.example.storage;

import com.fasterxml.jackson.databind.JsonNode;
import org.example.analytics.TradeRowParser;
import org.example.analytics.TradeSummaryRow;
import org.example.quik.dto.QuikMessage;
import org.example.quik.json.QuikJson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Локальный файл H2 в каталоге пользователя {@code ~/.quikclient/quik.*} — RPC, колбеки и нормализованные сделки.
 */
public final class H2QuikRepository implements AutoCloseable {

    static {
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            throw new ExceptionInInitializerError(new IllegalStateException(
                    "В classpath нет драйвера H2. Соберите fat-jar: mvn package, затем java -jar target/QuikClient-*-all.jar", e));
        }
    }

    private final String jdbcUrl;
    private Connection connection;

    public H2QuikRepository() throws SQLException, IOException {
        Path dir = Path.of(System.getProperty("user.home"), ".quikclient");
        Files.createDirectories(dir);
        Path base = dir.resolve("quik");
        String path = base.toAbsolutePath().toString().replace('\\', '/');
        this.jdbcUrl = "jdbc:h2:file:" + path + ";DB_CLOSE_DELAY=-1;AUTO_SERVER=FALSE";
        this.connection = DriverManager.getConnection(jdbcUrl);
        initSchema(connection);
    }

    private static void initSchema(Connection c) throws SQLException {
        try (Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS quik_rpc_result (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      operation VARCHAR(256) NOT NULL,
                      request_payload CLOB,
                      response_json CLOB NOT NULL,
                      lua_error VARCHAR(2048),
                      created_at TIMESTAMP NOT NULL
                    )""");
            st.execute("""
                    CREATE TABLE IF NOT EXISTS quik_callback (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      cmd VARCHAR(256) NOT NULL,
                      payload_json CLOB NOT NULL,
                      created_at TIMESTAMP NOT NULL
                    )""");
            st.execute("""
                    CREATE TABLE IF NOT EXISTS quik_trade_leg (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      rpc_result_id BIGINT NOT NULL,
                      class_code VARCHAR(64) NOT NULL,
                      sec_code VARCHAR(64) NOT NULL,
                      qty_lots BIGINT NOT NULL,
                      side VARCHAR(8) NOT NULL,
                      flags BIGINT NOT NULL,
                      trade_num_text VARCHAR(128),
                      created_at TIMESTAMP NOT NULL
                    )""");
            st.execute("CREATE INDEX IF NOT EXISTS idx_quik_rpc_created ON quik_rpc_result(created_at)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_quik_cb_created ON quik_callback(created_at)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_trade_leg_rpc ON quik_trade_leg(rpc_result_id)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_trade_leg_sec ON quik_trade_leg(sec_code)");
        }
    }

    public synchronized void saveRpc(String operation, String requestPayload, QuikMessage response) throws IOException, SQLException {
        String json = QuikJson.mapper().writeValueAsString(response);
        String luaErr = response.getLuaError();
        long rpcId;
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO quik_rpc_result(operation, request_payload, response_json, lua_error, created_at) VALUES (?,?,?,?,?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, operation);
            ps.setString(2, requestPayload);
            ps.setString(3, json);
            ps.setString(4, luaErr);
            ps.setTimestamp(5, Timestamp.from(Instant.now()));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (!keys.next()) {
                    throw new SQLException("Нет сгенерированного id для quik_rpc_result");
                }
                rpcId = keys.getLong(1);
            }
        }
        if ("get_trades_by_uid".equals(operation)
                && response.getData() != null
                && response.getData().isArray()
                && response.getLuaError() == null
                && !"lua_error".equals(response.getCmd())) {
            persistTradeLegs(rpcId, response.getData());
        }
    }

    private void persistTradeLegs(long rpcResultId, JsonNode tradesArray) throws SQLException {
        Timestamp now = Timestamp.from(Instant.now());
        String sql = """
                INSERT INTO quik_trade_leg(rpc_result_id, class_code, sec_code, qty_lots, side, flags, trade_num_text, created_at)
                VALUES (?,?,?,?,?,?,?,?)""";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            int batches = 0;
            for (JsonNode tr : tradesArray) {
                if (!tr.isObject() || !TradeRowParser.hasSecCode(tr)) {
                    continue;
                }
                long qty = TradeRowParser.qtyLots(tr);
                if (qty <= 0) {
                    continue;
                }
                String side = TradeRowParser.isSell(tr) ? "SELL" : "BUY";
                ps.setLong(1, rpcResultId);
                ps.setString(2, TradeRowParser.classCode(tr));
                ps.setString(3, TradeRowParser.secCode(tr));
                ps.setLong(4, qty);
                ps.setString(5, side);
                ps.setLong(6, TradeRowParser.flags(tr));
                ps.setString(7, TradeRowParser.tradeNumText(tr));
                ps.setTimestamp(8, now);
                ps.addBatch();
                batches++;
            }
            if (batches > 0) {
                ps.executeBatch();
            }
        }
    }

    /**
     * Сводка по последнему сохранённому набору сделок (максимальный {@code rpc_result_id} в {@code quik_trade_leg}).
     */
    public synchronized List<TradeSummaryRow> loadTradeSummaryForLastStoredBatch() throws SQLException {
        Long batchId = null;
        try (PreparedStatement ps = connection.prepareStatement("SELECT MAX(rpc_result_id) FROM quik_trade_leg")) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getObject(1) != null) {
                    batchId = rs.getLong(1);
                }
            }
        }
        if (batchId == null) {
            return List.of();
        }
        String sql = """
                SELECT class_code, sec_code,
                       SUM(CASE WHEN side = 'BUY' THEN qty_lots ELSE 0 END) AS bought,
                       SUM(CASE WHEN side = 'SELL' THEN qty_lots ELSE 0 END) AS sold
                  FROM quik_trade_leg
                 WHERE rpc_result_id = ?
                 GROUP BY class_code, sec_code
                 ORDER BY sec_code""";
        List<TradeSummaryRow> rows = new ArrayList<>();
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setLong(1, batchId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    long bought = rs.getLong("bought");
                    long sold = rs.getLong("sold");
                    rows.add(new TradeSummaryRow(
                            rs.getString("class_code"),
                            rs.getString("sec_code"),
                            bought,
                            sold,
                            bought - sold));
                }
            }
        }
        return rows;
    }

    public synchronized void saveCallback(QuikMessage msg) throws IOException, SQLException {
        String json = QuikJson.mapper().writeValueAsString(msg);
        String cmd = msg.getCmd() != null ? msg.getCmd() : "";
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO quik_callback(cmd, payload_json, created_at) VALUES (?,?,?)")) {
            ps.setString(1, cmd);
            ps.setString(2, json);
            ps.setTimestamp(3, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        }
    }

    public String jdbcUrl() {
        return jdbcUrl;
    }

    @Override
    public synchronized void close() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
            connection = null;
        }
    }
}
